name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker Tag'
        required: true
        default: 'latest'
jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dev:${{ github.event.inputs.dockerTag }}